package config

import (
	"5e/utils"
	"encoding/json"
)

type AutoGenerated struct {
	Success   bool    `json:"success"`
	Errcode   int     `json:"errcode"`
	Message   string  `json:"message"`
	Data      []AData `json:"data"`
	Timestamp int     `json:"timestamp"`
}

type AData struct {
	Match           []Match
	Season          int     `json:"season"`
	MatchCode       string  `json:"match_code"`
	MatchType       string  `json:"match_type"`
	GameType        string  `json:"game_type"`
	StartTime       string  `json:"start_time"`
	EndTime         string  `json:"end_time"`
	EndDate         string  `json:"end_date"`
	RoundTime       string  `json:"round_time"`
	Map             string  `json:"map"`
	Score1          string  `json:"score1"`
	Score2          string  `json:"score2"`
	Kill            string  `json:"kill"`
	IsMVP           string  `json:"is_mvp"`
	IsMost1v2       string  `json:"is_most_1v2"`
	IsMostHeadshot  string  `json:"is_most_headshot"`
	IsMostFirstKill string  `json:"is_most_first_kill"`
	IsMostEnd       string  `json:"is_most_end"`
	IsMostAWP       string  `json:"is_most_awp"`
	IsMostJump      string  `json:"is_most_jump"`
	IsWin           string  `json:"is_win"`
	RWS             string  `json:"rws"`
	Rating          string  `json:"rating"`
	DemoURL         string  `json:"demo_url"`
	Death           string  `json:"death"`
	KD              float64 `json:"kd"`
	PerHeadshot     string  `json:"per_headshot"`
	Kill5           string  `json:"kill_5"`
	Kill10          int     `json:"kill_10"`
	Assist          string  `json:"assist"`
	IsCreditMatch   int     `json:"is_credit_match"`
}

type Match struct {
	Data     string
	Name     string
	Teammate string
	Avatar   string
	Up       int
	Nameid   string
}
type Acco struct {
	Match        []Match
	Nameid       string
	Name         string
	Location     int
	Teammate     string
	Teammate_ids []string
	MatchCode    string
}

func (this *Match) Match() {

	//this.Data = utils.ExtractTextBetween(data, "name tleft ban-bg", "icon_wrap")
	//for _, v := range this.Data {
	this.Name, _ = utils.ExtractTextBetweenone(this.Data, "username-tooltips\">", "</span>")
	this.Teammate, _ = utils.ExtractTextBetweenone(this.Data, "class=\"formation", "icon-titletip")
	this.Avatar, _ = utils.ExtractTextBetweenone(this.Data, "avatar\" src=\"", "\"")
	this.Nameid, _ = utils.ExtractTextBetweenone(this.Data, "https://arena.5eplay.com/data/player/", "\"")
	//}
}

func Deserialize(b []byte) (*AutoGenerated, error) {
	var a AutoGenerated
	err := json.Unmarshal(b, &a)
	if err != nil {
		return nil, err
	}

	return &a, nil
}
